---
title: "sta 183 final project"
author: "Michelle Tsang"
date: "12/6/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## set up data

```{r}
byss <- read.csv("Byssinosis.csv")

## wide to long
n <- nrow(byss)
countColumns <- c(which(names(byss) == "Byssinosis"), which(names(byss) ==
                                                              "Non.Byssinosis"))
longByss <- rbind(cbind(Byss=1,byss[rep(1:n, byss[,"Byssinosis"]), -countColumns]),
                  cbind(Byss=0, byss[rep(1:n, byss[,"Non.Byssinosis"]), -countColumns])
)
row.names(longByss) <- 1:nrow(longByss)

```


## long form but really big BIC
```{r}
workspace_factor = with(longByss, factor(Workspace))
glm_full = glm(factor(Byss)~Employment+Smoking+Sex+Race+workspace_factor,
               family=binomial, data=longByss)

summary(glm_full)
BIC(glm_full)
```

## wide form
```{r}
glm_fullwide = glm(cbind(Byssinosis, Non.Byssinosis) ~ Employment+Smoking+Sex+Race+
                     factor(Workspace), family = binomial, data = byss)
summary(glm_fullwide)
BIC(glm_fullwide)
```
### diagnostic plots
```{r}
plot(glm_fullwide)
```

### testing for independence between workspace and byssinosis
```{r}
## likelihood ratio test
myGlm = glm(cbind(Byssinosis, Non.Byssinosis)~factor(Workspace), 
            family = binomial, data = byss)
myGlm20 <- glm(cbind(Byssinosis, Non.Byssinosis)~1, family = binomial, data = byss)
LRstat <- -2*(logLik(myGlm20)-logLik(myGlm))
## statistic:
anova(myGlm20, myGlm)
## p-value:
1-pchisq(anova(myGlm20, myGlm)[2, 4],2)
```
### CI for log odds
```{r}
## CI's for log-odds of Y=1 if x=0
est <- coef(myGlm)[1]
estSE <- sqrt(vcov(myGlm)[1, 1])
ci2 <- c(est + qnorm(0.05/2)*estSE, est - qnorm(0.05/2)*estSE)
ci2
```

### glm for each workspace dustiness
```{r}
work1 <- with(byss, Workspace==1)
work2 <- with(byss, Workspace==2)
work3 <- with(byss, Workspace==3)

glm(cbind(Byssinosis, Non.Byssinosis) ~ Employment+Smoking, family=binomial,
    data=byss[work1,])$coef
glm(cbind(Byssinosis, Non.Byssinosis) ~ Employment+Smoking, family=binomial,
    data=byss[work2,])$coef
glm(cbind(Byssinosis, Non.Byssinosis) ~ Employment+Smoking, family=binomial,
    data=byss[work3,])$coef

glm(cbind(Byssinosis, Non.Byssinosis) ~ Employment+Smoking, family=binomial,
    data=byss)$coef
```
